<?php

/**
 * @file
 * A module for testing Entity Print.
 */

/**
 * Implements hook_system_theme_info().
 */
function entity_print_test_system_theme_info() {
  $themes['entity_print_test_theme'] = drupal_get_path('module', 'entity_print_test') . '/themes/entity_print_test_theme/entity_print_test_theme.info';
  return $themes;
}

/**
 * Implements hook_entity_print_css().
 */
function entity_print_test_entity_print_css_alter(&$render, $entity) {
  $render['#attached']['library'][] = 'entity_print_test_theme/module';
}
